PATH_CLIENTI = 'Dati/Clienti2.pickle'
PATH_PORTAFOGLI = 'Dati/Portafogli2.pickle'
PATH_CONTRATTI = 'Dati/Contratti2.pickle'
PATH_VEICOLI = 'Dati/Veicoli2.pickle'
PATH_BACKUP = 'Dati/Backup2.pickle'
PATH_CURRENT_USER = 'Dati/CurrentUser2.pickle'
PATH_CURRENT_WALLET = 'Dati/CurrentWallet2.pickle'
